apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test
spec:
  description: >-
    This task runs unit tests on the source code
  params:
    - name: source-repo
      description: The git repository that contains the source code
      type: string
  workspaces:
    - name: source
      description: The workspace containing the source code
  steps:
    - name: run-tests
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        set -e
        echo "Installing dependencies..."
        pip install --no-cache-dir pipenv
        
        echo "Setting up virtual environment..."
        pipenv install --dev
        
        echo "Running unit tests..."
        pipenv run pytest tests/ -v --junitxml=test-results.xml
        
        echo "Unit tests completed successfully!"
