apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test
spec:
  description: |
    This task runs unit tests on the source code
  workspaces:
    - name: source
      description: The workspace containing the source code
  steps:
    - name: test
      image: python:3.9
      workingDir: $(workspaces.source.path)
      script: |
        pip install pytest pytest-cov pytest-spec pipenv
        pipenv install --system --dev
        export RETRY_COUNT=1
        pytest --pspec --cov=service --cov-fail-under=95 --disable-warnings
