apiVersion: v1
kind: Secret
metadata:
  name: postgres-creds
  labels:
    app: postgres
data:
  password: cG9zdGdyZXM=
  database_uri: cG9zdGdyZXNxbCtwc3ljb3BnOi8vcG9zdGdyZXM6cG9zdGdyZXNAcG9zdGdyZXM6NTQzMi9wb3N0Z3Jlcw==
